T391 1 dev test docker
gwu-libraries/scholarspace-hyrax pull request #477
Opened 2024-01-09 04:56 UTC by alepbloyd

# PR 1 of 3 for being able to run automated test and CI/CD (#391) 

Tried to separate out just the code changes related to Docker and Rails environments that are needed for running RSpec tests and running in development mode in Docker, so the immediate benefits of these changes may not be evident. After testing of this PR, next are changes required for setting up RSpec and other testing gems, followed by the RSpec tests. 

The biggest changes are: 
- The naming of the Hyrax databases, Fedora databases, and Solr cores. These have been refactored to just be set with a single `.env` variable each, and automatically appends `_dev` and `_test` in configurations for consistency. 
- Changing default bind mounts for backup Fedora and Solr data on local machine.
- Changing the Rails default/dev server to use Passenger rather than Puma
- Fixing `json-canonicalization` gem error
- Exposing port 3000 in `docker-compose` so we can use Rails development server
- Rather than using templates to map files in/out of docker container, use non-template versions - easier when developing in development mode in docker container. 

# To test: 
- Build and start docker containers:
  - `docker-compose build`
  - `docker-compose up -d`
  - (or however else you manage docker containers, e.g. VSCode extension)
- Follow README instructions to set up in `production` mode, either following instructions for restoring from backup data, or creating a new production instance (e.g. `docker exec -it --user scholarspace [app-server-container-name] bash -lc "rails db:{drop,create,migrate,seed}"`)
- Follow the instructions in the "Development Mode" portion of the README to prepare, launch, and stop a development instance accessible via port 3000. If successful, you should be able to interact with the development instance and the production instance simultaneously in different browser tabs.

2024-01-19 18:23 UTC, kerchner requested changes
@alepbloyd The changes to move configurations out of the `.yml` files (and `hyrax.rb` and environment/*.rb) and into `.env` environment variables, avoiding the need to copy from example files and edit, work well and greatly smooth out the deployment process.

A couple of issues I encountered related to changes in this branch (at least the first item is):
- Due to changes to `:add_admin_role`, this rake task can no longer be used in a production setup.  Recommend updating either the task or, if not, the README to document the method (rails console, if need be) for adding a user to the admin role.
- Not entirely sure, but I think there is no step in the current README that directs the reader to perform db migrations for a new production environment.

2024-01-19 20:40 UTC, alepbloyd commented
@kerchner 

Thanks for reviewing this! Just made changes that I think fixes those issues.

- Added instructions for migrating the prod DB. 

- Created a new rake task `gwss:prep_new_prod`, that takes arguments of `admin_user` and `admin_password`, and then runs the steps to create that admin user, create the needed admin sets as well as an `ETDs` admin set, and then precompiles assets for prod. You should be able to run this just after migrating the prod DB, and it should handle the rest of the setup to get to a functional empty prod instance with that admin user/password. 

Command all together ends up like: 
`bundle exec rails gwss:prep_new_prod RAILS_ENV=production admin_user="AN-EMAIL-ADDRESS@EXAMPLE.COM" admin_password="A-PASSWORD"`

2024-01-21 02:07 UTC, kerchner approved these changes

2024-01-21 02:08 UTC, kerchner commented
@alepbloyd Thanks for the new rake task and README changes.  Works great.  No further issues. :+1:

2024-01-22 17:16 UTC, merged